version: "3.9"

services:
  hugging-face:
    image: oblivion208/huggingface-pytorch-jupyter:gpu
    tty: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    ipc: "host"
    ports:
      - 8888:8888
    working_dir: /app
    volumes:
      - ./:/app
